### ISSUE TITLE
README issues

### ISSUE THREAD

**Issue by amis92** [BSData/this-is-not-a-test#1]
This readme is quite helpful, but it needs to contain some parts of the template readme (https://github.com/BSData/TemplateDataRepo#readme)

* badges as they were (reason: I use them for quick overview when browsing through repos)
* Links section (reason: those links are important for navigation around organization)

Consider including some part of Overview section as well, currently there's no explanation how to report bugs, for example (with a link to battlescribedata.appspot.com).

---

From stability point of view, please don't include third party links to datafiles - I'm referring to http://battlescribe.mattcaron.net/this_is_not_a_test/index.bsi

Datafiles should be downloaded via http://battlescribedata.appspot.com/#/repo/this-is-not-a-test website, and at best simply though Manage Data dialog in the app itself.

**Comment by andreanespeca** [comment]
All done as requested, thanks to report this issue

**Comment by amis92** [comment]
Thanks!
